### ISSUE TITLE
QGS filerne læses forskelligt af forskellige qgis versioner

### ISSUE THREAD

**Issue by Telling** [Kortforsyningen/Qgis_plugin_Kortforsyningen#13]
Jeg kan f.eks. ikke åbne orto forår laget i min qgis (2.8.0), hvorimod det virkede på Martins med qgis 2.8.1.

**Comment by MieWinstrup** [comment]
Er ikke længere aktuelt da der fra version 1.0 bruges qlrfil fremfor QGIS-projektfil.
