### ISSUE TITLE
Nye DHM produkter mangler

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/Qgis_plugin_Kortforsyningen#22]
Jævnfør http://kortforsyningen.dk/indhold/den-nye-dhm-flytter-ind-i-wmsdhm er de seneste DHM produkter nu tilgængelige via WMS. Det drejer sig om både terræn og overflade model (inkl. skyggekort). De bør tilføjes Kortforsyningen-menuen hurtigst muligt, så brugerne ikke fejlagtigt benytter forældede data.

**Comment by MieWinstrup** [comment]
Ja, det skal de da!

Tom Weber ved hvordan dette skal gøres. Det er desuden beskrevet her:https://github.com/Kortforsyningen/Qgis_plugin_Kortforsyningen/wiki/Drift-og-vedligeholdelse-af-Kortforsyningsplugin (under 'Ændring af kategorier og WMS-lag i plugin')

I skal overveje om I ønsker at beholde de gamle data i Kortforsyningspluginet eller fjerne kategorien.

Arbejdsprocessen er:
1. Opret et nyt QGIS-projekt der indeholder de nye data, stylet som I ønsker dem. Husk at lagene i lag-panelet i QGIS-projektet skal arrangeres så de giver bedst mening.

2. Erstat brugernavn og kodeord til WMS-services (som beskrevet i github wiki)

3. Gem QGIS-projektet på jeres server sammen med de andre qgis-projekter

4. Tilføj kategorinavn og sti til qgisprojektet i json-filen (som også er gemt på jeres server)

(5. Hvis I ønsker at fjerne 2007-data, så skal referencen til disse fjernes fra json-filen)

**Comment by DocDemar** [comment]
Plugin er opdateret med den nye højdemodel
