### ISSUE TITLE
Opgradering af plugin til Qgis 3.x

### ISSUE THREAD

**Issue by DocDemar** [Kortforsyningen/Qgis_plugin_Kortforsyningen#23]
Når tiden kommer skal plugin understøtte både Qgis version 2.xx og 3.x

**Comment by larsnaesbye** [comment]
API breaks er indtil videre her: https://github.com/qgis/QGIS/blob/master/doc/api_break.dox

- og kommer endeligt ud ved release på:  https://qgis.org/api/api_break.html
