### ISSUE TITLE
Uncaught ImportError: No module named QtWebKit.QWebView


### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/Qgis_plugin_Kortforsyningen#27]
Couldn't load plugin Kortforsyningen due to an error when calling its classFactory() method
Steps to reproduce
1. First 
2. Second 
3. Third 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bjorn/.qgis2/python/plugins/Kortforsyningen/__init__.py", line 34, in classFactory
    from .kortforsyningen import Kortforsyningen
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bjorn/.qgis2/python/plugins/Kortforsyningen/kortforsyningen.py", line 38, in <module>
    from kortforsyningen_about import KFAboutDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bjorn/.qgis2/python/plugins/Kortforsyningen/kortforsyningen_about.py", line 28, in <module>
    os.path.join(os.path.dirname(__file__), 'aboutKortforsyningen.ui')
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 43, in <module>
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named QtWebKit.QWebView

```

The above causes installation error if QWebView is missing in the local Python distribution. Would probably make sense to make it's use optional functionality.
Kortforsyningen 0.1, QGIS 2.14.7-Essen on Linux 4.7.0-1-amd64

**Comment by bjornharrtell** [comment]
The cause of this problem is most likely because Debian is transitioning to QT5 while QGIS 2 and this plugin was written for QT4. Closing as QT5 migration for QGIS will happen not before QGIS 3 as far as I know so will have to revisit at that time.

**Comment by larsnaesbye** [comment]
This is still happening with plugin 1.0, QGIS 2.14.11-Essen, Ubuntu 17.04.

Should we document this somewhere in web space?

**Comment by bjornharrtell** [comment]
Reopening. Regardless of underlying issues I think this should be fixable in this plugin code.

**Comment by larsnaesbye** [comment]
Yes, since we don't know when QGIS 3 is out, we might follow [an approach like this](https://stackoverflow.com/questions/19282255/qwebview-on-qt4-and-qt5) in the meantime.

**Comment by MieWinstrup** [comment]
Agreed with Jørgen: 
For Debian-users, don't show the about-dialog, but add a dialogbox which points towards https://apps2.kortforsyningen.dk/qgis_knap_config/Kortforsyningen/kf/about.html in order to solve this issue.

**Comment by kjoller** [comment]
The underlying issue is that QtWebKit has been removed from the standard Debian/Ubuntu PyQt4 packages. 

However, the python-qgis package adds it back in. So it is not that the QtWebKit module was not there, it was just missing a 'definition' file for being able to create a dialog dynamically from a Qt Designer file (a .ui).

After I reported the bug, @jef-n was really helpful by adding it in qgis/QGIS@c39e4fc, so it should be landing in the relevant packages at some point. I don't know the release process, so I am not sure when that point will be.

I still think, that it would be a good idea to make the plugin able to run, even if QtWebKit is not working, so I will still look into an alternative, simpler about dialog in case of failure.

**Comment by jef-n** [comment]
The next point release is on friday (see [release schedule](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule))

**Comment by larsnaesbye** [comment]
Cool! Will this be backported to 2.14?

**Comment by jef-n** [comment]
qgis/QGIS@96ada08

**Comment by kjoller** [comment]
Would it make sense just having the menu entry ("About the plugin") open the link in the user's browser?

**Comment by DocDemar** [comment]
In my view -  In the  case of error 'QWebViewit is missing' it would be OK - as long as we alert the user that clicking the link will open a browser session outside Qgis.
