### ISSUE TITLE
Create qlr-files to use for testing new version of Kortforsyningsplugin

### ISSUE THREAD

**Issue by MieWinstrup** [Kortforsyningen/Qgis_plugin_Kortforsyningen#30]
Create:
* One qlr that represent the qlr-file that Kortforsyningen will serve (no layers with restricted access, including layernames and groupnames with danishletters).
* One qlr that represent the qlr-file that Kortforsyningen will serve (including layers with restricted access).
* One qlr that represent a qlr-file that a municipality would like to add to the Kortforsyningsplugin

Upload to labs.

**Comment by MieWinstrup** [comment]
They are now uploade to labs (with code commit in Septima labs github repo 297920b7ebc3f37d05778f59e2fdafff681e8aa5).

* korforsyning_data.qlr: Represent a qlr file that Kortforsyningen will serve. Contains four groups (some of these groups have 'æ' and 'ø'). None of the layers have data access restriction. Some of the layers have 'æ', 'ø' and 'å' in their name.

* kortforsyning_data_inkl_restricteddata.qlr: Represent a qlr file that Kortforsyningen will serve. This include layers with restricted access and hence more like the file Kortforsyningen will serve. The layers with restricted layers are in two groups - one group (Fotdata) just with restricted layers. The group 'Geografiske grænser' contains not-restricted layers and one restricted layer (Kommune fot).
 
* individual_data.qlr: Represent a qlr-file that a municipality would like to add to the Kortforsyningsplugin. This qlr-file contains 3 WMS layers with layers from Kortforsyningen and GEUS.

**Comment by klavspc** [comment]
labs.septima.dk/qgis-kf-knap/
