### ISSUE TITLE
Fejl på Win7

### ISSUE THREAD

**Issue by GregersP** [Kortforsyningen/Qgis_plugin_Kortforsyningen#31]
Flg er observeret på en række Win7-maskiner:

![image](https://cloud.githubusercontent.com/assets/2797067/21000217/df5f8f86-bd19-11e6-8729-3edb0d9d842a.png)

Fejlen kom straks ved install, og pluginnet virker ikke (starter tilsyneladende ikke op).

**Comment by DocDemar** [comment]
Er den nuværende version af plugin omfattet af dette problem?

**Comment by AsgerPetersen** [comment]
@GregersP Kan du sige noget mere om:

- QGIS-installationen (Er det Osgeo4W eller standalone)
- Stien til plugins-mappen. Python kan ikke så godt lide specialtegn i stien.

**Comment by GregersP** [comment]
@DocDemar det er ved download hos en kunde i går - så det er seneste releasede version.

@AsgerPetersen  Jeg prøver at undersøge - jeg har ikke selv adgang til milieuet

**Comment by GregersP** [comment]
PROFILE (dvs. userdir) er: c:\Users\mlkr\
QGIS er så vidt jeg er orienteret installeret ved OSGEO4W

**Comment by DocDemar** [comment]
sagen lukkes da problemet ikke kan genskabes
