### ISSUE TITLE
Ingen pulldown liste med de sædvanlige temaer fra kortforsyningen

### ISSUE THREAD

**Issue by Geodataodense** [Kortforsyningen/Qgis_plugin_Kortforsyningen#42]
Plugin kører ikke korrekt på nyinstalleret pc..  Nogen idé. Jeg har prøvet at slette "C:\Users\xxxx\.qgis2\python\plugins\Kortforsyningen" og geninstallere hele QGIS
![2017-09-22_0944](https://user-images.githubusercontent.com/18719005/30735912-f83d247e-9f80-11e7-98c0-677d7bd8c5d0.png)

Problemet findes kun på denne pc

**Comment by zimzar11** [comment]
Jeg har samme problem. Har du fundet ud af det?

**Comment by Geodataodense** [comment]
Prøv i settings at henvise til qlr-fil.  Der er kommet en ny mulighed for at tilføje egne lag..  Men det lader til at man skal henvise til placeringen af den qlr-fil der følger med plugin.

<img width="249" alt="2018-01-29 10_55_49-kortforsyningen - settings" src="https://user-images.githubusercontent.com/18719005/35504380-d3de8568-04da-11e8-8c4c-b8c1dbf3f445.png">

**Comment by Sonder79** [comment]
Normalt skal man ikke henvise til den qlr-fil som følger med installationen af pluginnet.
Meningen er at man skal kunne lave sin egen qlr-fil med f.eks egne data, som man evt. vil dele med andre i ens organisation el. lign.

**Comment by Geodataodense** [comment]
:-) Det er en workaround..  Vi kan jo spørge Kortforsyningen eller Septima om det er en bug de vil rette

**Comment by Sonder79** [comment]
Her er Kortforsyningen. Her virker det som det skal. Er det alle hos jer som har problemet.
Hilsen Tom

**Comment by MieWinstrup** [comment]
Problemet kan skyldes konflikt med din web-sikkerhedsindstilling, der ikke tillader at pluginet henter en qlr-fil fra Kortforsyningen. Dette er andre steder blevet løst ved at url'en til qlr-filen (http://apps2.kortforsyningen.dk/qgis_knap_config/Kortforsyningen/kf/kortforsyning_data.qlr) tilføjes som tilladt ekstern opkobling.

**Comment by zimzar11** [comment]
Det virker nu mange tak for hjælpen. Blev nød til at henvise til qlr-filen
