### ISSUE TITLE
Fejl ved håndtering af qlr-filer, hvor der er noget 'galt' med et eller flere af lagene

### ISSUE THREAD

**Issue by MieWinstrup** [Kortforsyningen/Qgis_plugin_Kortforsyningen#43]
Hvis en bruger tilføjer deres egen qlr-fil, hvori et eller flere af lagene i denne qlr-fil, af en eller anden grund, ikke kan håndteres af pluginet, så bliver pluginet ubrugeligt (pluginet forsvinder). Den eneste måde, hvormed brugeren kan få pluginet tilbage er ved at omdøbe (eller slette) den qlr-fil som pluginet peger på. Fejlen opstår bl.a. ved nogle af lagene fra GEUS' WMS (http://data.geus.dk/geusmap/ows/25832.jsp?VERSION=1.1.1). En bruger har desuden rapporteret samme fejl ved brug af historiske luftfotos.

Det bør rettes så:
 - Brugeren får en besked om, at der er 'ugyldige' lag i qlrfilen - og at indstillingsmenuen bevares, så brugeren kan fjerne denne qlrfil.
 - Det bør undersøges hvorfor disse lag fejler og om det kan rettes.

![image](https://user-images.githubusercontent.com/16276034/33420745-07fccc6a-d5b0-11e7-9dad-3110f5c2e5f8.png)

Problemet gør sig både gældende i pluginet til QGIS 2 og QGIS 3.

**Comment by DocDemar** [comment]
Det må i meget gerne rette i både den eksisterende og den nye version af plugin.
Jeg tænker at vi skal lave et nyt deploy af den eksisterende plugin med rettelsen

**Comment by MieWinstrup** [comment]
Fint.
