### ISSUE TITLE
Error starting Kortforsyning plugin in Qgis 2.18.22

### ISSUE THREAD

**Issue by giskonsulenten** [Kortforsyningen/Qgis_plugin_Kortforsyningen#49]
Error messages fra Qgis:

2018-10-16T09:22:43	1	Traceback (most recent call last):
			  File "C:/Users/Forsyning/.qgis2/python/plugins\Kortforsyningen\kortforsyningen.py", line 156, in <lambda>
			    kf_helper = lambda _id: lambda: self.open_kf_node(_id)
			  File "C:/Users/Forsyning/.qgis2/python/plugins\Kortforsyningen\kortforsyningen.py", line 222, in open_kf_node
			    layer = self.open_node(node, id)
			  File "C:/Users/Forsyning/.qgis2/python/plugins\Kortforsyningen\kortforsyningen.py", line 225, in open_node
			    QgsProject.instance().read(node)
			  File "C:/Users/Forsyning/.qgis2/python/plugins\profiletool\apicompat\qgsproject.py", line 55, in read
			    return original_QgsProject_read(self, QFileInfo(filename))
			TypeError: arguments did not match any overloaded call:
			  QFileInfo(): too many arguments
			  QFileInfo(QString): argument 1 has unexpected type 'QDomNode'
			  QFileInfo(QFile): argument 1 has unexpected type 'QDomNode'
			  QFileInfo(QDir, QString): argument 1 has unexpected type 'QDomNode'
			  QFileInfo(QFileInfo): argument 1 has unexpected type 'QDomNode'

**Comment by TW2018** [comment]
Hvornår opstår beskeden? Er det når pluginnet startes op? 
Vh. Tom Weber, Kortforsyningen

**Comment by giskonsulenten** [comment]
Det opstår ved valg af et kort.
Har lige konstateret, at det er hvis Plugin'et Profile tool er installeret. Kortforsyningen fungerer efter afinstallation af Profile Tool og genstart af Qgis.
Men vil nødigt undvære Profile Tool :-)

mvh
Jesper Jøker Eg

**Comment by TW2018** [comment]
Er det først opstået i 2.18.22? Har ikke hørt om problemet fra andre.

**Comment by giskonsulenten** [comment]
Samme issue i 2.14.13

**Comment by TW2018** [comment]
Kan godt se der opstår konflikt hvis man installerer Profile Tool i QGIS 2.18.21.
I QGIS 3.2 Bonn virker begge dele sammen. Har du prøvet i QGIS 3?

**Comment by MieWinstrup** [comment]
Problemet i Kortforsyningspluginet opstår fordi Profile Tool pluginet aktivt overskriver variablen qgis.core.QgsProject.read med en metode, der ikke virker med det nye "node" system.

Problemet i Profile Tool er rapporteret her:
https://github.com/PANOimagen/profiletool/issues/13

**Comment by JaviBecerra** [comment]
Hi,
We are working in a fix on the ProfileTool plugin; if you want to try a fix while we get this properly checked and pushed, you can edit profiletool/apicompat/qgsproject.py and replace the read function with the following:
```
def read(self, param=None):   
    if param:
        try:
            return original_QgsProject_read(self, QFileInfo(param))
        except TypeError:
            return original_QgsProject_read(self, param)
    else:
        return original_QgsProject_read(self)
```
We have not been able to reproduce the issue with Kortforsyning plugin, but we expect this to fix it.

**Comment by JaviBecerra** [comment]
We have just uploaded Profiletool plugin version 4.1.4 to QGis repos adressing this issue.
Regards,
Javier

**Comment by MieWinstrup** [comment]
Det ser ud til at den nye version af profile-tool-pluginet fungerer fint samtidig med at Kortforsyningspluginet også fungerer.

@JaviBecerra - thanks for making a new version of profile tool very fast!
